run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 100
  misspell:
    locale: US
  goimports:
    local-prefixes: ssh-plex

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-dirs:
    - .kiro
    - build
    - dist
  exclude-use-default: true
  exclude:
    # Allow fmt.Fprintf and similar functions without error checking in dry-run output
    - Error return value of .fmt\.Fprint.*. is not checked
    # Allow session.Signal without error checking (best effort)
    - Error return value of .session\.Signal. is not checked
    # Allow connection close without error checking (cleanup)
    - Error return value of .*\.Close. is not checked
    # Allow InsecureIgnoreHostKey for now (TODO item)
    - Use of ssh InsecureIgnoreHostKey should be audited
    # Allow file operations (they're validated elsewhere)
    - Potential file inclusion via variable
    # Allow weak random for jitter (not cryptographic)
    - Use of weak random number generator
  max-issues-per-linter: 50
  max-same-issues: 3