# ssh-plex Configuration Example
# Copy this file to config.yaml and customize as needed

# Execution settings
concurrency: "auto"          # Number of concurrent connections ("auto" or number)
retries: 2                   # Maximum retry attempts per target
timeout: "5m"                # Total execution timeout (0 for unlimited)
cmd-timeout: "60s"           # Per-command timeout

# Output settings
output: "streamed"           # Output format: "streamed", "buffered", "json"
quiet: false                 # Suppress non-error output

# Logging settings
log-level: "info"            # Log level: "info", "error"
log-format: "text"           # Log format: "text", "json"

# Default host settings (optional)
# hosts: "user@host1,user@host2"
# hostfile: "hosts.txt"

# Note: SSH settings like default port, user, and identity file
# are not configurable via config file in the current version.
# Use host specification format instead:
# user@hostname:port?key=/path/to/key.pem